on: push
name: Publish to servers
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to Tadema Studio 
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 185.51.247.125
        FTP_USERNAME: ikaserg
        FTP_PASSWORD: ${{ secrets.zomro_hosting_ftp }}
        LOCAL_DIR: client/php
        REMOTE_DIR: /www/studio-tadema.net
        ARGS: --include=control_files.php

      