on: push
name: Publish to servers
jobs:
  Client-deploy-Action:
    name: Client-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to Tadema Studio 
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 185.51.247.125
        FTP_USERNAME: ikaserg
        FTP_PASSWORD: ${{ secrets.zomro_hosting_ftp }}
        LOCAL_DIR: client/php
        REMOTE_DIR: /www/studio-tadema.net
        ARGS: --include=control_files.php

  Server-Deploy-Action:
    name: Server-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to Server side 
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 77.83.173.244
        FTP_USERNAME: ${{ secrets.zomro_login }}
        FTP_PASSWORD: ${{ secrets.zomro_ftp }}
        LOCAL_DIR: server
        REMOTE_DIR: /file_control/
        ARGS: --include=delete_injected.py

     